[List] Fix horizontal divided list first item extra padding
fomantic/Fomantic-UI pull request #1159
Opened 2019-11-12 20:32 UTC by sergei-krylov

## Description
Fixes horizontal divided list first item extra padding.
All the details here in bug: #1158 

## Testcase
https://jsfiddle.net/sergei_krylov/zu39pxo5/2/

## Closes
#1158

2019-11-12 20:39 UTC, y0hami approved these changes
LGTM

2019-11-12 21:28 UTC, exoego requested changes
LGTM

2019-11-12 22:28 UTC, lubber-de commented
`:not(:first-child)` was already there for horiznotal divided lists.
We removed it by #353 to make sure those items will still align identically when wrapped on mobile devices, so i am against merging this PR.

Look at your adjusted jsfiddle and try to reduce the screen width until the list wraps, then your fix introduces the old wrapping bug again which, imho, is more important to fix
https://jsfiddle.net/Lcht5mpa/
![image](https://user-images.githubusercontent.com/18379884/68716190-f49d9e80-05a3-11ea-8a52-aad80093101f.png)

2019-11-12 23:18 UTC, lubber-de commented
Here is a proposal for goodness 😉 
If we implement a new `unstackable` class and add your suggested fix for the fist-childs left padding, we can satisfy both of us

See https://jsfiddle.net/6u1pmhsc/1/
![image](https://user-images.githubusercontent.com/18379884/68718934-fdde3980-05aa-11ea-8914-989491f60255.png)

2019-11-13 07:29 UTC, sergei-krylov commented
@lubber-de thanks! #353 is a good point that I missed. This definitely makes sense and important for equal-width items so they wrap into straight columns, and probably less important when the list contains items of various widths.

Adding such `unstackable` will add variety to lists, good proposal btw, but it's kind of separate thing as it still does not solve the issue if I have some long horizontal list and really want it to be "stackable".

Let's not go further with these changes so far. I'm using FUI on my project and maybe will get into another solution for both use cases.

_Yeah, I will update only LESS files next time_ :pray:

2019-11-13 07:29 UTC, closed without merging