fix(dropdown): calculate correct height of current menu if it contains child menu
fomantic/Fomantic-UI pull request #1779
Opened 2020-11-24 22:08 UTC by ko2in

## Description
When the menu contain the child menu, the calculation of menu height is incorrect while evaluating to open upward or downard.

It's because the child menu is hidden when the current menu is in the transition of being open and it doesn't occupy any space in the current menu and the height of the current menu is incorrectly calculated without the height of child menu which let the menu opens upward or downward incorrectly.

This PR checks if the current menu has the child menu and adds the child menu height to the current menu height to give correct assumption whether the menu fits in the screen upward or downward.

![Dropdown](https://user-images.githubusercontent.com/930315/100156761-dd440180-2ed7-11eb-8374-6a7de90e4c48.gif)

## Testcase

Open the fiddle and adjust the page where the dropdown is not fit to open downward. Click the button to open dropdown. The dropdown should open upward.
- Bug: https://jsfiddle.net/ko2in/k6Lwzhjf/
- Fixed: https://jsfiddle.net/ko2in/c28t6wkx/

## Screenshot
**Incorrect:**
![Dropdown-Downward](https://user-images.githubusercontent.com/930315/100156466-5db63280-2ed7-11eb-8dd1-f7c9c672dedc.gif)

**Correct:**
![Dropdown-Upward](https://user-images.githubusercontent.com/930315/100156473-6149b980-2ed7-11eb-9a86-e783383b0b53.gif)

## Closes
#1711

2020-11-24 22:20 UTC, ko2in reviewed
Please review this one. I chose the selector incorrectly in previous commit.

2020-11-24 23:41 UTC, lubber-de requested changes
When this code is used on a multilevel submenu the opening of the 2nd level submenu will return NaN for outerHeight on undefined, because it will always check the most parent menu. Supplying the currentmenu to the `.has.subMenu` method to support nested dropdowns fixes that . There won't be a console error though, but the resulting calculations.height is NaN in those cases.

I suggested some changes at the related codelines to fix it.

Try this dropdown to reproduce
```javascript
<div class="ui dropdown button">
  <span class="text">Choose Category</span>
  <i class="dropdown icon"></i>
  <div class="menu">
    <div class="item">
      <span class="text">Category 1</span>
    </div>
    <div class="item">
      <i class="dropdown icon"></i>
      <span class="text">Category 2</span>
      <div class="menu">
        <div class="item">Item 2A</div>
        <div class="item">Item 2B</div>
        <div class="item">Item 2C</div>
      </div>
    </div>
    <div class="item">
      <i class="dropdown icon"></i>
      <span class="text">Category 3</span>
      <div class="menu">
        <div class="item">Item 3A</div>
        <div class="item">Item 3B</div>
        <div class="item">Item 3C</div>
      </div>
    </div>
  </div>
</div>
```

2020-11-24 23:41 UTC, lubber-de commented on src/definitions/modules/dropdown.js
> +            return $menu.find(selector.menu).length > 0;
This has to respect a multilevel submenu
```suggestion
          subMenu: function($subMenu) {
            return ($subMenu || $menu).find(selector.menu).length > 0;
```

2020-11-24 23:41 UTC, lubber-de commented on src/definitions/modules/dropdown.js
> +            if(module.has.subMenu()) {
Submenu has alto to respect multi nested submenus
```suggestion
            if(module.has.subMenu($currentMenu)) {
```

2020-11-25 10:04 UTC, ko2in reviewed
@lubber-de Please review again. I used the argument name `subMenu: function($currentMenu)` because, it refers to the current menu.

Shouldn't the `openDownward` check only for first-level menu? I thought only the first level menu opens upward or downward, but from second level, all menus open leftward or rightward.

2020-11-25 10:16 UTC, lubber-de commented
> I used the argument name `subMenu: function($currentMenu)` because, it refers to the current menu.
> 
While this is fine as long as this method is only used internally, i still suggest to make the menu argument optional, so it can be used as behavior or in other parts of the code.

```javascript
return ($currentMenu || $menu).find(selector.menu).length > 0;
```
making `$currentMenu` optional will make this also work as externally called behavior. All other `.has` methods also work this way (yes, those always refer to the most parent menu anyway)


> Shouldn't the `openDownward` check only for first-level menu? I thought only the first level menu opens upward or downward, but from second level, all menus open leftward or rightward.

That's logical, yes. But nevertheless the fix was needed anyway (`has.submenu` was checking for $menu always, while the inner `if` was referencing `$currentMenu` instead)

2020-11-25 12:02 UTC, ko2in reviewed
OK. Here we go again. The menu selector is optional now. If it doesn't pass specific menu node, it'll use the root menu node instead.

2020-11-25 12:51 UTC, lubber-de approved these changes
LGTM  👍

2020-11-26 02:21 UTC, exoego approved these changes
LGTM
Document needed ?

2020-11-26 09:49 UTC, ko2in commented
No. The fix and changes are internal use only.

2020-11-26 09:51 UTC, merged