[Security] Solved Regular Expression Denial of Service vulnerability caused by gulp-concat-css
fomantic/Fomantic-UI pull request #1860
Opened 2021-02-02 20:32 UTC by phiberber

## Description
The plugin [gulp-concat-css](https://www.npmjs.com/package/gulp-concat-css) was using the [rework-import](https://www.npmjs.com/package/rework-import) package, which was using the outdated version of url-regex, causing it to have a vulnerability "Regular Expression Denial of Service". I forked the gulp-concat-css and rework-import repositories and uploaded the "safe" version of them to npm. That should be a good fix as the repositories probably aren't going to update anytime soon.

## Closes
#1646

2021-02-02 20:38 UTC, phiberber commented
Seems the problem is related to the re2 module not being found (similar issue [here](https://github.com/dilame/instagram-private-api/issues/1328)). Even though the dependency is already in the [url-regex-safe package](https://developer.aliyun.com/mirror/npm/package/url-regex-safe).

2021-02-03 21:09 UTC, lubber-de commented
@phiberber Please adjust your forked version so it does not use re2 (mentioned [here](https://github.com/dilame/instagram-private-api/issues/1328#issuecomment-744001078))
It has to be buildable OS independant. You most probably were testing it on windows only.

2021-02-03 21:12 UTC, lubber-de requested changes
Try to fix the re2 issue like here 
https://github.com/dilame/instagram-private-api/pull/1334

It has to be buildable on linux as well

2021-02-04 12:43 UTC, phiberber commented
I'm closing this Pull Request, Node-re2 doesn't seem to be stable enough to be used in Fomantic UI (or in any framework imo). Guess we should wait until [Eugene](https://github.com/uhop) creates a version of node-re2 that doesn't use node-gyp, or [url regex safe](https://github.com/niftylettuce/url-regex-safe) stops using node-re2. I tried at least 🤔.

2021-02-04 12:43 UTC, closed without merging