fix(modal): Hiding dimmer with multiple modals
fomantic/Fomantic-UI pull request #2444
Opened 2022-08-30 19:49 UTC by mareeo

## Description
This PR moves the check for other active/animating modals to hide the dimmer to the hide animation complete instead of the hide animation start.

## Testcase

## Screenshot (if possible)
Original
![Original](https://user-images.githubusercontent.com/9520224/187529679-265b5ce9-ea9a-42c5-96db-383b0c9c5e2a.gif)

After change
![Fix](https://user-images.githubusercontent.com/9520224/187529706-7be0a5dd-95c3-4072-9381-840407b226d6.gif)

## Closes
#2441

2022-08-30 20:09 UTC, lubber-de commented
Thanks for the PR, it basically works. However, hiding the dimmer after (even if just one) modal is hidden, is somehow disturbing the design/flow of the modal. 
What if we just add the same code to onComplete (as you did but inside the `if ( settings.allowMultiple ) {` condition because this issue only happens on multiple modals, isn't it?) , but keep the code at onStart as well? Doesn't this also fix your issue?

2022-08-30 22:20 UTC, mareeo commented
Good catch, the my change caused the modal hide animation to start only once the modal was hidden. I've made the change you suggested and it does appear to work. If this edge case is reached, the dimmer will still start to hide once the modal is hidden, but I guess that's better than previous behavior of the dimmer not hiding at all.

One potential catch with this change, if you display a single modal with `allowMultiple` and then hide it, `hideDimmer()` is now called on the modal hide animation start and complete.  This doesn't break anything, but it does result in the debug message "Animation is already occurring, will not execute repeated animation" if you have debug mode enabled.

I'd like to add a condition to prevent this, but I'd need some way to know if the dimmer is animating out as opposed to just simply animating (which is what it's doing now by calling the dimmer's `is animating`). I could check if the dimmer has the `out` class to determine if it's animating out and prevent duplicate calls in modal's `hideDimmer()`.

2022-08-31 20:07 UTC, lubber-de requested changes
Please see my comment.
Regarding "avoid the debug info by checking for the 'out' class"
Well, the hideDimmer function does also support _not_ using css classes, so if someony possibly uses `dimmerSettings: {useCss:false}` checking for the out class won't work.

The issue you mention actually comes from the "hideAll" function rather than your new change in the onComplete method.

So, instead, i suggest to check if "hide dimmer" is still in progress.
You can accomplish this by  centrally adjusting the `hideDimmer` method as follows :

### First: create new module wide variable `isHiding`
Snippet:
```javascript
    time           = new Date().getTime(),
    performance    = [],
    isHiding       = false,
```

### Second: Adjust the hideDimmer method to check for that variable like this

Snippet
```javascript
        hideDimmer: function() {
          if(!isHiding && ($dimmable.dimmer('is animating') || ($dimmable.dimmer('is active'))) ) {
            isHiding = true;
            module.unbind.scrollLock();
            $dimmable.dimmer('hide', function() {
              isHiding = false;
              module.restore.bodyMargin();
              module.remove.clickaway();
              module.remove.screenHeight();
            });
          }
          else {
             module.debug('Dimmer is not visible cannot hide');
            return;
          }
        },
```

2022-09-08 17:43 UTC, lubber-de commented
@mareeo Will you continue to work on this?

2022-09-10 14:27 UTC, mareeo commented
I plan to, just limited on time currently. Thanks for the detailed reply and suggestion, I'll give it a go once I have time

2026-01-14 07:35 UTC, closed without merging