feat(calendar): "get date" can return formatted date
fomantic/Fomantic-UI pull request #3141
Opened 2024-12-23 03:32 UTC by dreaming-augustin

```
$('.ui.calendar').calendar('get date');
$('.ui.calendar').calendar('get focusDate');
$('.ui.calendar').calendar('get startDate');
$('.ui.calendar').calendar('get endDate');

```
could so far only return a Javascript Date object.

Now, given a `format` argument, they return a formatted date string:

```
$('.ui.calendar').calendar('get date',      "YYYY-MM-DD");
$('.ui.calendar').calendar('get focusDate', "YYYY-MM-DD");
$('.ui.calendar').calendar('get startDate', "YYYY-MM-DD");
$('.ui.calendar').calendar('get endDate',   "YYYY-MM-DD");

```

The `format` string is passed to the existing formatter.

This is backward compatible as the default behaviour does not change.

It makes it convenient for developers to get exactly what they need when they need it.

2024-12-25 18:02 UTC, lubber-de requested changes
Please see my comments / suggestions.
The new code is now somewhat duplicated four times (using a different metadata value) we should even think of putting that in a unique function

2024-12-25 18:02 UTC, lubber-de commented on src/definitions/modules/calendar.js
> +                        return module.helper.dateFormat(format, $module.data(metadata.endDate));
1. Default function parameter values are not supported in IE11 (which FUI 2.9.x still supports)
2. I would reduced the call to the sanitisedate function
```suggestion
                        format = format || '';
                        if (endModule) {
                            return endModule.get.date(format);
                        }
                        
                        var endDate = module.helper.sanitiseDate($module.data(metadata.endDate)) || null;
                        if (!endDate) {
                            return null;
                        }

                        if (format === '') {
                            return endDate;
                        }

                        return module.helper.dateFormat(format, endDate);
```

2024-12-26 04:47 UTC, dreaming-augustin commented
> 1. Default function parameter values are not supported in IE11 (which FUI 2.9.x still supports)

Ok. I am fluent in JavaScript. I think more in term of C++, so I couldn't imagine parameters that were undefined.

2024-12-26 05:21 UTC, dreaming-augustin commented
> The new code is now somewhat duplicated four times (using a different metadata value) we should even think of putting that in a unique function

 Done. You make suggest another function name...

2024-12-26 12:08 UTC, lubber-de approved these changes
Thanks, but cleaner! LGTM
Please take a short look at your docs PR where i was already commenting https://github.com/fomantic/Fomantic-UI-Docs/pull/524

2024-12-26 12:08 UTC, lubber-de commented
Docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/524

2024-12-26 12:22 UTC, dreaming-augustin commented
Thank you for your reviews.
I apologize for dumping so many PR just before Christmas!  
I hope you had/are having great holidays.

2024-12-26 13:27 UTC, merged