[Search] Inject id and class attr into individual result
fomantic/Fomantic-UI pull request #3142
Opened 2024-12-23 12:56 UTC by dreaming-augustin

Give much more flexibility on the type of content and theming possibilities for each individual search result.

We could already manipulate the response received by the Search API:

```
onResponse: function(original_response) {
    var response = {
       results : {}
    };
    $.each(original_response.results, function(index, item) {
          // Manipulate each item.
          // Possibly add item.id
         // Possibly add item.classes
    }
    return response;
}
```

The problem is that we couldn't inject the `id` and `class` attributes to each individual item rendered by the Search module.

Now, depending on the status of each response, the status potentially reflecting a given website's logic and needs, we can inject an id and additional classes that can then be used for theming and manipulating.

Also, before each item was wrapped within a `<a>` tag. Because HTML prohibits having nested `<a>` tags (which makes sense), we couldn't inject any link into the body of individual items (e.g. inject relevant links to open in a different browser tab, while keeping the result popup menu open).

Now, if the result item has `result[fields.url]`, then keep the `<a>` tag, because it makes sense: the whole result is assigned an URL.
If `result[fields.url]` is absent, the result is wrapped within a `<div>` tag, making it possible to inject one or even several links into the result's description, as may be required.

This feature is backward-compatible, as the default behavior is unchanged.

2024-12-23 13:15 UTC, dreaming-augustin commented
If requested, I can submit a PR for documentation later.

2024-12-23 13:23 UTC, dreaming-augustin commented
Here are two examples of theming achieved with this new feature: 

![Fomantic-search-classes-PR3142-2024-12-23-1](https://github.com/user-attachments/assets/d7ffdc66-860e-4825-8030-bd265f008b7f)
![Fomantic-search-classes-PR3142-2024-12-23-2](https://github.com/user-attachments/assets/6d890585-047d-4e4a-8d3c-6d546a61c152)

2024-12-25 20:06 UTC, lubber-de requested changes

2024-12-25 20:06 UTC, lubber-de commented on src/definitions/modules/search.js
> +                            : '</div>';
See above, this should be reverted to always create an achor `a` tag

2024-12-25 20:06 UTC, lubber-de commented on src/definitions/modules/search.js
> +                        html += result[fields.classes] !== undefined
we should rename the fields property to `class` ins tead of `classes`

2024-12-25 20:06 UTC, lubber-de commented on src/definitions/modules/search.js
> +                                html += result[fields.classes] !== undefined
we should rename the fields property to `class` ins tead of `classes`

2024-12-25 20:06 UTC, lubber-de commented on src/definitions/modules/search.js
> +                                    : html += '<div ';
Not needed and a breaking change, keep using the anchor tag

2024-12-25 20:06 UTC, lubber-de commented on src/definitions/modules/search.js
> +                                    : '</div>';
See above and revert. Keep using the anchor tag

2024-12-25 20:06 UTC, lubber-de commented on src/definitions/modules/search.js
> +            classes: 'classes', // Classes specific to each result to add to the HTML 'class' attribute.
We should name the property `class`  instead of `classes`

2024-12-25 20:12 UTC, lubber-de requested changes

2024-12-25 20:12 UTC, lubber-de commented on src/definitions/modules/search.js
> +                                    ? ' class="result ' + result[fields.classes] + '">'
needs to be sanitized (double quotes removed)
```suggestion
                                    ? ' class="result ' + result[fields.classes].replace(/"/g, '') + '">'
```

2024-12-25 20:12 UTC, lubber-de commented on src/definitions/modules/search.js
> +                                    ? ' id="' + result[fields.id] + '" '
Needs to be sanitzed (doubple quotes removed
```suggestion
                                    ? ' id="' + result[fields.id].replace(/"/g, '') + '" '
```

2024-12-25 20:12 UTC, lubber-de commented on src/definitions/modules/search.js
> +                            ? ' id="' + result[fields.id] + '" '
Needs to be sanitized (double quotes removed)
```suggestion
                            ? ' id="' + result[fields.id].replace(/"/g, '') + '" '
```

2024-12-25 20:12 UTC, lubber-de commented on src/definitions/modules/search.js
> +                            ? ' class="result ' + result[fields.classes] + '">'
Needs to be sanitized (double quotes removed)

2024-12-25 20:36 UTC, lubber-de commented
Seeing my comments, i currently disagree (or at least saying it's a breaking change) to the "use a div if no url exists" logic.
You can already provide a complete custom render template function as documented in https://fomantic-ui.com/modules/search.html#templates
Yes, this might need an improved docs page and perhaps an example as well

2025-09-25 19:48 UTC, lubber-de commented on src/definitions/modules/search.js
> +                            : '<div ';
As the next version allows for breaking changes, i now agree :)

2025-09-26 08:58 UTC, ko2in approved these changes
LGTM.

2025-10-18 19:15 UTC, lubber-de approved these changes

2025-10-18 19:16 UTC, merged

2025-10-18 19:18 UTC, lubber-de commented
@dreaming-augustin I finally agreed, fixed my requested changes in your PR and merged it.
As you suggested: If you like, you may create a proper docs example PR accordingly